### PR TITLE
Support for spliting measures to integer and fraction.

### PR DESCRIPTION
**Pull request by chernomor**
This PR allow to avoid division of measure. Instead we may split measure to two i16 values: integer and ten thousandth parts (fraction *10000).

P.S. May be I should not change signature of read_temperature() and should create read_temperature_raw()?

### CODE REVIEW

**Comment by kellerkindt** [comment]
Thanks. I am not entirely sure about the use case, but I am okay with merging it.
Could you push another commit with ruftmt being executed?

**Comment by chernomor** [comment]
@kellerkindt are your means rustfmt? Yes, I could, but it formats not only my changes, but whole crate. If you accept this - it's ok.

**Comment by kellerkindt** [comment]
Well, I meant applying rustfmt afterwards. But i`ll do it after the merge, so I dont have to annoy you with that.
Thanks for your contribution

**Comment by chernomor** [comment]
Oh, I applied rustfmt to crate, then picked my original commit and forgot to format it - I'm sorry :(
Thanks for correcting my mistake!

**Pull request merged**
