### PR TITLE
Fixup warnings

### PR DESCRIPTION
**Pull request by TDHolmes**
get rid of all warnings and update to non-deprecated APIs.

### CODE REVIEW

**Comment by kellerkindt** [comment]
Sou... why did you close this PR? ^^

**Comment by TDHolmes** [comment]
To be honest I assumed you weren’t maintaining this anymore since you hadn’t replied to my issue haha. I meant to make the PR against my fork

**Comment by kellerkindt** [comment]
Well, this has not been fixed :)

**Comment by TDHolmes** [comment]
What do you mean?

**Pull request closed without merging**
